stages:
  train:
    cmd: python utils/classifier/train.py
    deps:
    - utils/classifier/train.py
    params:
    - train.seed
    - train.model_name
    - train.dataset
    - train.epochs
    - train.steps_per_epoch
    - train.batch
    - train.loss
    - train.learning_rate
  evaluate:
    cmd: python utils/classifier/evaluate.py utils/classifier/dvc_objects/model/saved_model.pb utils/classifier/dvc_objects/scores.json prc.json roc.json
    deps:
    - utils/classifier/dvc_objects/model/saved_model.pb
    - utils/classifier/evaluate.py
    metrics:
    - utils/classifier/dvc_objects/scores.json:
        cache: false
