train:
  seed: 123
  model_name: "Plantabit_custom_tarbil_2"
  dataset: "1_rawdata_clean"
  epochs: 105
  steps_per_epoch: 5
  batch: 128
  loss: "categorical_crossentropy"
  learning_rate: 0.001
  l2_reg: 0.0005
  momentum: 0.9
