train:
  seed: 123
  model_name: "Plantabit_tarbil_2"
  dataset: "1_rawdata_clean"
  epochs: 100
  steps_per_epoch: 10
  batch: 128
  loss: "categorical_crossentropy"
  learning_rate: 0.001
  l2_reg: 0.0005
  momentum: 0.9
