train:
  seed: 123
  model_name: "Plantabit_tarbil_13"
  dataset: "0_rawdata"
  epochs: 105
  steps_per_epoch: 65
  batch: 128
  loss: "categorical_crossentropy"
  learning_rate: 0.001
  l2_reg: 0.0005
  momentum: 0.9
