train:
  seed: 123
  model_name: "Plantabit_transfer_vgg16_2"
  dataset: "2_rawdata_clean_no_duplicates"
  epochs: 50
  steps_per_epoch: 25
  batch: 32
  loss: "categorical_crossentropy"
  learning_rate: 0.001
  l2_reg: 0.0005
  momentum: 0.9
