train:
  seed: 123
  model_name: "Plantabit_custom_cnn_1"
  dataset: "2_rawdata_clean_no_duplicates"
  epochs: 100
  steps_per_epoch: 5
  batch: 128
  loss: "categorical_crossentropy"
  learning_rate: 0.001
  l2_reg: 0.0005
  momentum: 0.9
